# Generated by Django 2.1.2 on 2018-10-13 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paste',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='paste',
            name='hash',
        ),
        migrations.RemoveField(
            model_name='paste',
            name='size',
        ),
    ]
